# Generated by Django 5.0.6 on 2024-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post_ip',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
