# Generated by Django 5.0.6 on 2024-08-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0002_feedback_post_ip'),
        ('candidate', '0020_remove_wallpost_reply_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docsquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(db_comment='D for Directory and F for File', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Docsquad.docsquad')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.wallpostips')),
            ],
            options={
                'db_table': 'docsquad',
            },
        ),
    ]
