# Generated by Django 5.0.6 on 2024-08-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0003_docsquad'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsquad',
            name='privacy',
            field=models.CharField(db_comment='A for public and O for private', default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='docsquad',
            name='file_type',
            field=models.CharField(db_comment='D for Directory and F for File', max_length=1),
        ),
        migrations.AlterField(
            model_name='docsquad',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Docsquad.docsquad'),
        ),
    ]
