# Generated by Django 5.0.6 on 2024-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0004_docsquad_privacy_alter_docsquad_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsquad',
            name='disabled',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
