# Generated by Django 5.0.6 on 2024-08-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0005_docsquad_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsquad',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Docsquad.docsquad'),
        ),
    ]
