# Generated by Django 5.0.6 on 2024-08-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docsquad', '0008_alter_docsquad_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsquad',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
