# Generated by Django 5.0.6 on 2024-06-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('leave_days', models.CharField(max_length=50)),
                ('no_of_leaves', models.IntegerField()),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
    ]
