# Generated by Django 5.0.6 on 2024-06-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_leaverecords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaverecords',
            table='leave_records',
        ),
    ]
