# Generated by Django 5.0.6 on 2024-06-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_leaverecords_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('project_no', models.CharField(max_length=20)),
                ('workorder_no', models.CharField(max_length=20)),
                ('data_till', models.DateTimeField()),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'candidate_history',
            },
        ),
    ]
