# Generated by Django 5.0.6 on 2024-06-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidatehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverecords',
            old_name='leave_days',
            new_name='paid_leave_days',
        ),
    ]
