# Generated by Django 5.0.6 on 2024-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
