# Generated by Django 5.0.6 on 2024-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecords',
            name='att_details',
            field=models.FileField(default='', upload_to='attendance/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverecords',
            name='att_graph',
            field=models.FileField(default=None, upload_to='attendance/'),
            preserve_default=False,
        ),
    ]
