# Generated by Django 5.0.6 on 2024-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_leaverecords_att_details_leaverecords_att_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecords',
            name='att_details',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='leaverecords',
            name='att_graph',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
