# Generated by Django 5.0.6 on 2024-06-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_leaverecords_att_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecords',
            name='att_details',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='leaverecords',
            name='att_graph',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
