# Generated by Django 5.0.6 on 2024-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_leaverecords_att_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('files', models.FileField(upload_to='photos/')),
                ('posted_ip', models.CharField(max_length=15)),
                ('posted_time', models.DateField()),
            ],
            options={
                'db_table': 'wall_post',
            },
        ),
    ]
