# Generated by Django 5.0.6 on 2024-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_alter_wallpost_posted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='posted_by',
            field=models.CharField(default='Anonym.', max_length=30),
            preserve_default=False,
        ),
    ]
