# Generated by Django 5.0.6 on 2024-07-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_wallpost_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='disabled',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
