# Generated by Django 5.0.6 on 2024-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_wallpostips'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='subject',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
