# Generated by Django 5.0.6 on 2024-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_wallpost_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='reply_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='reply_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='reply_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='reply_ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallpost',
            name='reply_time',
            field=models.DateTimeField(null=True),
        ),
    ]
