# Generated by Django 5.0.6 on 2024-08-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_wallpost_reply_by_wallpost_reply_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpost',
            name='reply_id',
        ),
    ]
