# Generated by Django 5.0.6 on 2024-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_wallpostaccessrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpostips',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
